version: '3.1'

services:
  mongo-api:
    container_name: mongostudy
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ADMINUSERNAME}:${ADMINPASSWORD}@mongo:27017/
    # volumes:
      # - ./severapi:/data/db